name: Docker CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+-*'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: ${{ contains(github.ref_name, 'production') && 'production' || 'staging' }}
    steps:
    - uses: actions/checkout@v4

    - uses: docker/login-action@v3.4.0
      name: Log in to Docker Hub
      with:
        username: ${{ vars.DOCKER_ACCOUNT }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - uses: docker/metadata-action@5.7.0
      id: meta
      name: Docker metadata
      with:
        images: ${{ vars.DOCKER_ACCOUNT}}/${{ vars.DOCKER_REPOSITORY }}
        tags: |
            type=sha
            type=ref,event=tag
    - name: Environment variables injection
      run: |
          echo -e 'REACT_APP_API_URL=${{ secrets.API_URL }}\nREACT_APP_BACKEND_ECOMMERCE_URL=${{ secrets.BACKEND_ECOMMERCE_URL }}' > ./client/.env.production
          cat ./client/.env.production

    - uses: docker/build-push-action@v6.18.0
      name: Build and push
      with:
        context: client/.
        push: true
        tags: ${{ steps.meta.outputs.tags }}

    - name: Pull infra repository
      if: ${{ ! contains(github.ref_name, 'production') }}
      uses: actions/checkout@v4
      with:
        repository: '${{ secrets.REPO_INFRA_URL }}'
        ref: 'main'
        token: ${{ secrets.REPO_INFRA_ACCESS_TOKEN }}

    - name: Modify manifests
      if: ${{ ! contains(github.ref_name, 'production') }}
      run: |
          git config user.name "Github actions bot"
          git config user.email "<>"
          BRANCH=$( echo ${{ github.ref_name }} | sed -r 's/v[0-9]+.[0-9]+-//g' )
          sed -i -r 's/v[0-9]+.[0-9]+-(staging|production)/${{github.ref_name}}/g' ./overlays/$BRANCH/deployment_patch.yaml

    - name: Commit and push changes
      if: ${{ ! contains(github.ref_name, 'production') }}
      run: |
          git add .
          git commit -m "Updated manifests"
          git push -u origin main
